name: Test Semplice

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Saluta
        run: echo "Ciao mondo! Se vedi questo messaggio, il workflow funziona."
